# Generated by Django 3.2.9 on 2022-05-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Droit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myform.aide')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myform.personne')),
            ],
        ),
    ]
